-- AlterTable
ALTER TABLE "settings" ADD COLUMN     "emailFromAddress" TEXT,
ADD COLUMN     "emailFromName" TEXT DEFAULT 'Bella Pizza',
ADD COLUMN     "emailNotificationsEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "notificationsEnabled" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "notifyOnCancelled" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "notifyOnCompleted" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "notifyOnConfirmed" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "notifyOnDelivering" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "notifyOnPaymentFailed" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "notifyOnPreparing" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "notifyOnReady" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "smsNotificationsEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "smtpHost" TEXT DEFAULT 'smtp.gmail.com',
ADD COLUMN     "smtpPassword" TEXT,
ADD COLUMN     "smtpPort" INTEGER NOT NULL DEFAULT 587,
ADD COLUMN     "smtpSecure" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "smtpUser" TEXT,
ADD COLUMN     "twilioAccountSid" TEXT,
ADD COLUMN     "twilioAuthToken" TEXT,
ADD COLUMN     "twilioPhoneNumber" TEXT;
